name: Slack

on:
  pull_request_review
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Review notyfication to ArkadiuszDatka
        if: github.event.review.user.login != 'ArkadiuszDatka'
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: 'C03JVC3FK0E'
          slack-message: "${{ github.event.review.html_url }} ${{ github.event.review.user.login }}  "
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}