name: Slack

on:
  pull_request_review_comment:
    types: [created]
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'U03H3Q9BUBS'
        slack-message: "${{ github.event.comment.html_url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
