name: Slack

on:
  pull_request_review
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'C03GF79DSPM'
        slack-message: "${{ github.event.review.html_url }} ++ ${{ github.event.action }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
