name: Slack

on:
  pull_request:
    types: [opened, reopened, ready_for_review, locked, review_requested]
     
jobs:
  build:
    if: github.event.pull_request.draft != 1
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'C03GF79DSPM'
        slack-message: "${{ github.event.pull_request.html_url || github.event.head_commit.url }} ${{ github.event.pull_request.user.login }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
