name: Slack

on:
  pull_request:
    types: [opened, reopened]
    branches: [ develop2 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        channel-id: 'C03GF79DSPM'
        # For posting a simple plain text message
        slack-message: "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
