name: Slack

on:
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  slack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C03GF79DSPM\",\"text\":\"Hello world\"}'
      
